version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - mynet

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - mynet

  #Inintinlizing kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mynet

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - mynet

  #eureka-server
  eureka-server:
    image: haitamelhayani2002/eureka-server:latest
#    build: ./eurekaserver
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - zipkin
    networks:
      - mynet

  #api-gateway
  api-gateway:
    image: haitamelhayani2002/api-gateway-service
#    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - zipkin
      - eureka-server
    networks:
      - mynet

  #mailing-service
  mailing-service:
    image: haitamelhayani2002/mailing-service
#    build: ./mailingservice
    container_name: mailing-service
    depends_on:
      - eureka-server
      - api-gateway
      - broker
      - zipkin
    ports:
      - "8094:8094"
    networks:
      - mynet

  #registration-service
  registration-service:
    image: haitamelhayani2002/registration-service
#    build: ./registrationservice
    container_name: registration-service
    depends_on:
      - mysql-db
      - eureka-server
      - api-gateway
      - mailing-service
      - broker
      - zipkin
    ports:
      - "8090:8090"
    networks:
      - mynet

  #post-service
  post-service:
    image: haitamelhayani2002/post-service
#    build: ./postservice
    container_name: post-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql-db
      - eureka-server
      - api-gateway
      - broker
      - zipkin
      - registration-service
    ports:
      - "8091:8091"
    networks:
      - mynet

volumes:
  db_data:

networks:
  mynet: