server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
       defaultZone: http://eureka-server:8761/eureka


spring:
  application:
    name: api-gateway
  zipkin:
#    base-url: http://localhost:9411
    base-url: http://zipkin:9411
    sleuth:
      sampler:
        probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: registration-service
          uri: lb://REGISTRATION-SERVICE
          predicates:
            - Path=/authentication/**
        - id: registration-service-admin
          uri: lb://REGISTRATION-SERVICE
          predicates:
            - Path=/admin/**
        - id: registration-service-ensiasts
          uri: lb://REGISTRATION-SERVICE
          predicates:
            - Path=/ENSIASts/**
        - id: registration-service-logout
          uri: lb://REGISTRATION-SERVICE
          predicates:
            - Path=/logout
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/**
        - id: mailing-service
          uri: lb://MAILING-SERVICE
          predicates: Path=/mailing/**
        - id: Eureka-server
#          uri: http://localhost:8761
          uri: http://eureka-server:8761
          predicates: Path=/eureka/web
          filters: SetPath=/
        - id: eureka-server-static
#          uri: http://localhost:8761
          uri: http://eureka-server:8761
          predicates: Path=/eureka/**
