apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: registration-service
  name: registration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: registration-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/social-network-app-mynet: "true"
        io.kompose.service: registration-service
    spec:
      containers:
        - image: haitamelhayani2002/registration-service
          name: registration-service
          ports:
            - containerPort: 8090
          resources: {}
      restartPolicy: Always
status: {}
